sunricebit/CapstoneProject_SP24_G16

PoolComVnWebApplication/PoolComVnWebClient/Views/Login/Index.cshtml, PoolComVnWebApplication/PoolComVnWebClient/wwwroot/css/style.css
update register form: add register role
=> NamVu_FE_Update login.html

PoolComVnWebApplication/BusinessObject/Models/User.cs, PoolComVnWebApplication/DataAccess/AccoutDAO.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/AccountController.cs, PoolComVnWebApplication/PoolComVnWebAPI/DTO/AccountDTO.cs
Tao, lay tat ca, xem chi tiet, ban unban account
=> CRUBan Account

PoolComVnWebApplication/DataAccess/DataAccess.csproj, PoolComVnWebApplication/DataAccess/PlayerDAO.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/PlayerController.cs, PoolComVnWebApplication/PoolComVnWebAPI/DTO/MapperConfig.cs, PoolComVnWebApplication/PoolComVnWebAPI/DTO/PlayerDTO.cs, PoolComVnWebApplication/PoolComVnWebAPI/PoolComVnWebAPI.csproj, PoolComVnWebApplication/PoolComVnWebAPI/Program.cs
CRUD Player and Import data from excel to sql nhung vi database hien tai chua dung nen chi dua theo model de lam nen se can sua lai o ver sau
=> CRUD Player and Import data from excel to sql ver1

PoolComVnWebApplication/BusinessObject/Models/Player.cs, PoolComVnWebApplication/BusinessObject/Models/Tournament.cs, PoolComVnWebApplication/BusinessObject/Models/User.cs, PoolComVnWebApplication/BusinessObject/Models/poolcomvnContext.cs
xoá bảng tourplayer và để relation trực tiếp giữa player và tournament
=> xoá bảng tourplayer

PoolComVnWebApplication/PoolComVnWebClient/Controllers/HomeController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/Tournament.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Shared/_Layout.cshtml, PoolComVnWebApplication/PoolComVnWebClient/wwwroot/css/style.css
Modify user-menu in nav-menu, css tournamentPlayers
=> NamVu_FE_Add home/tournament

PoolComVnWebApplication/PoolComVnWebClient/Controllers/CreateTournamentController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepFiveArrange.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepFourAddBanner.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepOneCreateTournament.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepSixReview.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepThreeAddTable.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepTwoJoinList.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepTwoMember.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepTwoPlayerList.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/SystemRandom.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/UserCustom.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/UserRandom.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Shared/_CreateTournamentFiveLayout.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Shared/_CreateTournamentLayout.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Tournament/Index.cshtml, PoolComVnWebApplication/PoolComVnWebClient/wwwroot/css/style.css
NamVu_FE_Modify home/tournament
=> NamVu_FE_Add step 2 3 4 5 6 create tournament

PoolComVnWebApplication/BusinessObject/Models/MatchOfTournament.cs, PoolComVnWebApplication/BusinessObject/Models/Player.cs, PoolComVnWebApplication/BusinessObject/Models/PlayerInMatch.cs, PoolComVnWebApplication/BusinessObject/Models/PlayerInSoloMatch.cs, PoolComVnWebApplication/BusinessObject/Models/Tournament.cs, PoolComVnWebApplication/BusinessObject/Models/poolcomvnContext.cs, PoolComVnWebApplication/DataAccess/ClubDAO.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/ClubController.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/NewsController.cs, PoolComVnWebApplication/PoolComVnWebAPI/DTO/MatchesDTO.cs, PoolComVnWebApplication/PoolComVnWebAPI/DTO/PlayerInMatchDTO.cs
=> Dinh the nam

PoolComVnWebApplication/DataAccess/PlayerDAO.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/PlayerController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepTwoPlayerList.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepTwoPlayerSystem.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Shared/_CreateTournamentLayout.cshtml
=> Step2-API-Client

PoolComVnWebApplication/DataAccess/TableDAO.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/TableController.cs, PoolComVnWebApplication/PoolComVnWebAPI/DTO/MapperConfig.cs, PoolComVnWebApplication/PoolComVnWebAPI/DTO/TableDTO.cs, PoolComVnWebApplication/PoolComVnWebAPI/Program.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/CreateTournamentController.cs, PoolComVnWebApplication/PoolComVnWebClient/DTO/TableDTO.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepThreeAddTable.cshtml
Lấy data bàn của Club đang đăng nhập bằng Account là chủ của Club đó
=> Lấy dữ liệu bàn

PoolComVnWebApplication/DataAccess/TableDAO.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/TableController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/AuthenticationController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepThreeAddTable.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepTwoJoinList.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepTwoPlayerSystem.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Shared/_Layout.cshtml
Stp3 đã lưu và chuyển status bàn
=> Longnp client step3 create tour

PoolComVnWebApplication/PoolComVnWebClient/Controllers/ManagerController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/NewsDetail.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Manager/Index.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/NewsManage/AddNews.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/NewsManage/Index.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Shared/_Layout.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Shared/_TournamentLayout.cshtml, PoolComVnWebApplication/PoolComVnWebClient/wwwroot/css/style.css
=> NamVu_FE_Add manageAccountForAdmin

PoolComVnWebApplication/DataAccess/NewsDAO.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/NewsController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/AuthenticationController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/HomeController.cs, PoolComVnWebApplication/PoolComVnWebClient/DTO/LoginDTO.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepOneCreateTournament.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/CreateTournament/StepThreeAddTable.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/Index.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Shared/_CreateTournamentLayout.cshtml
Đẩy New mới nhất lên homepage, viết thêm api GetLastestNews, dùng Annotations để check input login
=> Đẩy New mới nhất lên homepage

PoolComVnWebApplication/Test/Program.cs
=> Chỉnh hàm test

PoolComVnWebApplication/PoolComVnWebClient/Controllers/HomeController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/Index.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/NewsDetail.cshtml
Khi ấn vào new ở Homepage sẽ vào newdetail và các new detail khác(cũng có thể ấn vào xem)
=> NewDetail ở Homepage

PoolComVnWebApplication/DataAccess/AccoutDAO.cs, PoolComVnWebApplication/PoolComVnWebClient/DTO/ChangePasswordDTO.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/NewsDetail.cshtml
Hiển thị form ngày tháng năm DetailNew
=> Hiển thị form ngày tháng năm DetailNew

PoolComVnWebApplication/PoolComVnWebAPI/Controllers/NewsController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/HomeController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/NewsManageController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/Club.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Shared/_Layout.cshtml
=> Đẩy view các club

PoolComVnWebApplication/PoolComVnWebClient/Controllers/ClubController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Shared/_Layout.cshtml
=> Sửa lại đường dẫn

PoolComVnWebApplication/PoolComVnWebClient/Controllers/ClubController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Club/CreateClub.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Tournament/TournamentBracketForManager.cshtml, PoolComVnWebApplication/PoolComVnWebClient/wwwroot/css/style.css
Modify popup tourBracketFormanager
=> NamVu_FE_Add createClub

PoolComVnWebApplication/DataAccess/NewsDAO.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/NewsController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/NewsManageController.cs, PoolComVnWebApplication/PoolComVnWebClient/DTO/PaginatedList.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/NewsManage/Index.cshtml
Phân trang, tìm kiếm NewManage
=> Phân trang, tìm kiếm NewManage

PoolComVnWebApplication/DataAccess/ClubDAO.cs, PoolComVnWebApplication/DataAccess/NewsDAO.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/ClubController.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/NewsController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/HomeController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/NewsManageController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/Club.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/Index.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/NewsManage/Index.cshtml
=> Phân trang, search, filter

PoolComVnWebApplication/PoolComVnWebClient/Controllers/HomeController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Club/Index.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/Club.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/Index.cshtml
giữ nguyên phần header khi chuyển trang
=> fix home/index

PoolComVnWebApplication/PoolComVnWebAPI/Controllers/NewsController.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/PlayerController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/HomeController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/Index.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/NewsDetail.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/NewsManage/Index.cshtml
Lấy các new có status là true và sửa lại phần hiển thị ảnh trong description newDetail
=> New và NewDetail

PoolComVnWebApplication/DataAccess/AccoutDAO.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/AuthenticationController.cs, PoolComVnWebApplication/PoolComVnWebAPI/DTO/ChangePasswordDTO.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/AuthenticationController.cs, PoolComVnWebApplication/PoolComVnWebClient/PoolComVnWebClient.csproj, PoolComVnWebApplication/PoolComVnWebClient/Views/Authentication/ChangePassword.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Shared/_Layout.cshtml
=> ChangePassword

PoolComVnWebApplication/PoolComVnWebClient/Controllers/CreateTournamentController.cs
=> sửa step 2

PoolComVnWebApplication/DataAccess/ClubDAO.cs, PoolComVnWebApplication/DataAccess/TournamentDAO.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/TournamentController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/TournamentController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Manager/Index.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Shared/_Layout.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Tournament/TournamentList.cshtml, PoolComVnWebApplication/PoolComVnWebClient/wwwroot/css/style.css
=> TournamentList

PoolComVnWebApplication/DataAccess/AddressDAO.cs, PoolComVnWebApplication/DataAccess/ClubDAO.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/AddressController.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/ClubController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/HomeController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/TournamentController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/Club.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Shared/_Layout.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Tournament/TournamentList.cshtml
filter home/club, update search tournamentList
=> Tournament/List, home/club

PoolComVnWebApplication/DataAccess/PlayerDAO.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/PlayerController.cs, PoolComVnWebApplication/PoolComVnWebAPI/Controllers/TableController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/CreateTournamentController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/TournamentController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Tournament/TournamentBracket.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Tournament/TournamentBracketForManager.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Tournament/TournamentDetailForManager.cshtml
commit controller tournament detail manager
=> Tournament manage

PoolComVnWebApplication/PoolComVnWebClient/Controllers/ClubController.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/HomeController.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Club/Index.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Home/Club.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/NewsManage/Index.cshtml, PoolComVnWebApplication/PoolComVnWebClient/Views/Tournament/TournamentList.cshtml
NewManage/Index fix lại phần search, TourList chỉnh hiển thị phân trang, Club/Index gắn phân trang clubpost
=> Club/Index, TourList, NewManage/Index

PoolComVnWebApplication/BusinessObject/Models/ClubPost.cs, PoolComVnWebApplication/PoolComVnWebClient/Controllers/ClubController.cs, PoolComVnWebApplication/PoolComVnWebClient/DTO/DistrictDTO.cs, PoolComVnWebApplication/PoolComVnWebClient/DTO/ProvinceDTO.cs, PoolComVnWebApplication/PoolComVnWebClient/DTO/WardDTO.cs, PoolComVnWebApplication/PoolComVnWebClient/Views/Club/Index.cshtml
=> CLubController
